
package org.openkoala.jbpm.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JBPMApplication", targetNamespace = "http://application.jbpm.openkoala.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JBPMApplication {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.ProcessInstanceVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryAllProcess", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryAllProcess")
    @ResponseWrapper(localName = "queryAllProcessResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryAllProcessResponse")
    public List<ProcessInstanceVO> queryAllProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessImage", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessImage")
    @ResponseWrapper(localName = "getProcessImageResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessImageResponse")
    public byte[] getProcessImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.ProcessInstanceVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryAllActiveProcess", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryAllActiveProcess")
    @ResponseWrapper(localName = "queryAllActiveProcessResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryAllActiveProcessResponse")
    public List<ProcessInstanceVO> queryAllActiveProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.TaskVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryErrorList", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryErrorList")
    @ResponseWrapper(localName = "queryErrorListResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryErrorListResponse")
    public List<TaskVO> queryErrorList();

    /**
     * 
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.ProcessVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcesses", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcesses")
    @ResponseWrapper(localName = "getProcessesResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessesResponse")
    public List<ProcessVO> getProcesses();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeProcessVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveProcessVariable")
    @ResponseWrapper(localName = "removeProcessVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveProcessVariableResponse")
    public void removeProcessVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.JbpmNode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessNodesFromPorcessInstnaceId", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessNodesFromPorcessInstnaceId")
    @ResponseWrapper(localName = "getProcessNodesFromPorcessInstnaceIdResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessNodesFromPorcessInstnaceIdResponse")
    public List<JbpmNode> getProcessNodesFromPorcessInstnaceId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPorcessImageStream", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetPorcessImageStream")
    @ResponseWrapper(localName = "getPorcessImageStreamResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetPorcessImageStreamResponse")
    public byte[] getPorcessImageStream(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startProcess", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.StartProcess")
    @ResponseWrapper(localName = "startProcessResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.StartProcessResponse")
    public long startProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setProcessInstanceVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetProcessInstanceVariable")
    @ResponseWrapper(localName = "setProcessInstanceVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetProcessInstanceVariableResponse")
    public void setProcessInstanceVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeGlobalVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveGlobalVariable")
    @ResponseWrapper(localName = "removeGlobalVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveGlobalVariableResponse")
    public void removeGlobalVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "repairTask", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RepairTask")
    @ResponseWrapper(localName = "repairTaskResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RepairTaskResponse")
    public void repairTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delegate", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.Delegate")
    @ResponseWrapper(localName = "delegateResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.DelegateResponse")
    public void delegate(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeProcessInstance", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveProcessInstance")
    @ResponseWrapper(localName = "removeProcessInstanceResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemoveProcessInstanceResponse")
    public void removeProcessInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPackageVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetPackageVariable")
    @ResponseWrapper(localName = "setPackageVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetPackageVariableResponse")
    public void setPackageVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPakcages", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetPakcages")
    @ResponseWrapper(localName = "getPakcagesResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetPakcagesResponse")
    public List<String> getPakcages();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setProcessVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetProcessVariable")
    @ResponseWrapper(localName = "setProcessVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetProcessVariableResponse")
    public void setProcessVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessByPackage", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessByPackage")
    @ResponseWrapper(localName = "getProcessByPackageResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessByPackageResponse")
    public List<String> getProcessByPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setGlobalVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetGlobalVariable")
    @ResponseWrapper(localName = "setGlobalVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.SetGlobalVariableResponse")
    public void setGlobalVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProcess", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.AddProcess")
    @ResponseWrapper(localName = "addProcessResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.AddProcessResponse")
    public void addProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.openkoala.jbpm.wsclient.ProcessInstanceVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessInstance", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessInstance")
    @ResponseWrapper(localName = "getProcessInstanceResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessInstanceResponse")
    public ProcessInstanceVO getProcessInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.HistoryLogVo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryHistoryLog", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryHistoryLog")
    @ResponseWrapper(localName = "queryHistoryLogResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryHistoryLogResponse")
    public List<HistoryLogVo> queryHistoryLog(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeTask", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.CompleteTask")
    @ResponseWrapper(localName = "completeTaskResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.CompleteTaskResponse")
    public boolean completeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removePackageVariable", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemovePackageVariable")
    @ResponseWrapper(localName = "removePackageVariableResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.RemovePackageVariableResponse")
    public void removePackageVariable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignToNode", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.AssignToNode")
    @ResponseWrapper(localName = "assignToNodeResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.AssignToNodeResponse")
    public void assignToNode(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.JbpmNode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessNodes", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessNodes")
    @ResponseWrapper(localName = "getProcessNodesResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.GetProcessNodesResponse")
    public List<JbpmNode> getProcessNodes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.TaskVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryDoenTask", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryDoenTask")
    @ResponseWrapper(localName = "queryDoenTaskResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryDoenTaskResponse")
    public List<TaskVO> queryDoenTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.openkoala.jbpm.wsclient.TaskVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTodoList", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryTodoList")
    @ResponseWrapper(localName = "queryTodoListResponse", targetNamespace = "http://application.jbpm.openkoala.org/", className = "org.openkoala.jbpm.wsclient.QueryTodoListResponse")
    public List<TaskVO> queryTodoList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
