
package org.openkoala.jbpm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceApplication", targetNamespace = "http://application.jbpmDemo.jbpm.openkoala.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceApplication {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskUser", targetNamespace = "http://application.jbpmDemo.jbpm.openkoala.org/", className = "org.openkoala.jbpm.ws.GetTaskUser")
    @ResponseWrapper(localName = "getTaskUserResponse", targetNamespace = "http://application.jbpmDemo.jbpm.openkoala.org/", className = "org.openkoala.jbpm.ws.GetTaskUserResponse")
    public String getTaskUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "logMessage", targetNamespace = "http://application.jbpmDemo.jbpm.openkoala.org/", className = "org.openkoala.jbpm.ws.LogMessage")
    @ResponseWrapper(localName = "logMessageResponse", targetNamespace = "http://application.jbpmDemo.jbpm.openkoala.org/", className = "org.openkoala.jbpm.ws.LogMessageResponse")
    public void logMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
